name: opencv-debian

on:
  push:
    paths:
      - '.github/workflows/opencv-debian.yml'
      - 'opencv.Dockerfile'
      - '.version'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
      - uses: docker/setup-buildx-action@master
      - name: setup buildx
        run: |
          cat > ~/.docker/config.json << EOF
          ${{ secrets.DOCKER_CONFIG }}
          EOF
      - run: cd opencv-debian && make build
