name: opencv-debian-base

on:
  push:
    paths:
      - '.github/workflows/opencv-debian.yml'
      - 'opencv.Dockerfile'
      - '.version'


jobs:
  buildx-amd64:
    runs-on: ubuntu-latest
      #- self-hosted
      #- amd64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - run: make opencv.base-amd64
  buildx-arm64:
    runs-on: ubuntu-latest
    #  - self-hosted
    #  - ARM64
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - run: make opencv.base-arm64
