# name: opencv-debian

# on:
#   push:
#     paths:
#       - '.github/workflows/opencv-debian.yml'
#       - 'opencv.Dockerfile'
#       - '.version'

# jobs:
#   buildx:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: docker/setup-qemu-action@master
#       - uses: docker/setup-buildx-action@master
#       - uses: docker/login-action@v1
#         with:
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           username: ${{ secrets.DOCKER_USERNAME }}
#       - run: make opencv
